name: 'GitHub Advanced Security Licence Cleanup'
author: 'NickLiffen'
description: 'This GitHub Action informs you of repositories you could disable GitHub Advanced Security on to save some licences based on criteria.'
inputs:
  org:
    description: 'The GitHub Org Name that you would like to cleaup GHAS Licences On'
    required: true
  url:
    description: 'The GitHub URL. The default is github.com, but you '
    required: false
    default: 'https://api.github.com'
  level:
    description: 'verbose|precise (see README.md for more details)'
    required: false
    default: 'precise'
  dryrun:
    description: 'Tells the action wether to disable GHAS on the repositories specified'
    required: false
    default: 'true'
outputs:
  success:
    description: 'Did it work'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'target'  
  color: 'blue'
