name: 'Action Name'
author: 'NickLiffen'
description: 'Action Description'
inputs:
  org:
    description: 'The GitHub Org Name that you would like to cleaup GHAS Licences On'
    required: true
  url:
    description: 'The GitHub URL. The default is github.com, but you '
    required: false
    default: 'https://api.github.com'
  level:
    description: 'verbose|precise (see README.md for more details)'
    required: false
    default: 'precise'
  dryrun:
    description: 'Tells the action wether to remove the users found'
    required: false
    default: 'true'
outputs:
  success:
    description: 'Did it work'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'target'  
  color: 'blue'