--- 
jobs: 
  regression: 
    name: regression
    runs-on: ubuntu-20.04
    steps: 
      - 
        name: "Git Checkout"
        uses: actions/checkout@v4
      - 
        env: 
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
        name: "Licence Checker"
        uses: ./
        with: 
          org: ${{ secrets.ORG }} 
          url: "https://api.github.com"
          level: "precise"
          dryrun: "true"
      - 
        env: 
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
        name: "Licence Checker"
        uses: ./
        with: 
          org: ${{ secrets.ORG }} 
          url: "https://api.github.com"
          level: "verbose"
          dryrun: "true"
name: "Regression Testing - GHAS Licence Checker (Non Dependabot)"
? "on"
: 
  push:
    branches-ignore:
      - 'dependabot/**'