--- 
jobs: 
  regression-dependabot: 
    name: Regression Testing Dependabot
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') && github.event.sender.login == 'dependabot[bot]' }}
    runs-on: ubuntu-20.04
    steps: 
      - 
        name: "Git Checkout"
        uses: actions/checkout@v2
      - 
        env: 
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
        name: "Licence Checker"
        uses: ./
        with: 
          org: ${{ secrets.ORG }} 
          url: "https://api.github.com"
          level: "precise"
          dryrun: "true"
      - 
        env: 
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
        name: "Licence Checker"
        uses: ./
        with: 
          org: ${{ secrets.ORG }} 
          url: "https://api.github.com"
          level: "verbose"
          dryrun: "true"
name: "Regression Testing - GHAS Licence Checker (Dependabot)"
? "on"
: 
  pull_request_target: